//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerkanPortfolyo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int ID { get; set; }
        public string PhotoUrl { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public string SocialiconUrl { get; set; }
        public string Sociallink1 { get; set; }
        public string SocialiconUrl2 { get; set; }
        public string Sociallink2 { get; set; }
        public string SocialiconUrl3 { get; set; }
        public string Sociallink3 { get; set; }
        public string WhoisMe { get; set; }
        public string WhoisMeDescription { get; set; }
    }
}
